include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"