name: with_bloc
description: A widget to create and manage BLoCs.
version: 1.0.0
authors:
- Timm Preetz <timm.preetz@aboutyou.com>
- Henri Beck <henri.beck@aboutyou.com>
homepage: https://github.com/aboutyou/with_bloc

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.7.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^0.5.0

  collection: ^1.14.0

  meta: ^1.0.0
    
dev_dependencies:
  test: any

  state_queue:
   path: ../state_queue

  flutter_test:
    sdk: flutter
