name: with_bloc
description: A widget to create and manage BLoCs implemented on top of ValueNotifier, such as StateQueue.
version: 3.0.0-nullsafety.0
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/with_bloc
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-3.0.pre <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.10.0-nullsafety.2

  state_queue:
    path: ../state_queue

  test: any
