name: with_bloc
description: A widget to create and manage BLoCs implemented on top of ValueNotifier, such as StateQueue.
version: 3.0.0
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/with_bloc
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

  state_queue:
    path: ../state_queue

  test: any
