name: state_queue_test
description: Testing utilities for `StateQueue`
version: 2.0.0
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/state_queue_teste
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

  state_queue: ^3.0.0

  test: ^1.16.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
