name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:v1.12.13-hotfix.8

    steps:
      - uses: actions/checkout@v1
      - name: Setup permissions
        run: sudo chown -R cirrus /__w && sudo chmod -R 777 /__w
      - name: Install dependencies
        run: ./install_all.sh
      - name: Analyze
        run: ./analyze_all.sh
      - name: Run tests
        run: ./test_all.sh

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@c1bf65eb311fe29b5bc99d6e91c4498decde268a # v1.3.0
        with:
          flutter-version: "1.12.13+hotfix.8"
      - run: dart --version
      - run: flutter --version
      - name: Install dependencies
        run: ./install_all.sh
      - name: Analyze
        run: ./analyze_all.sh
      - name: Run tests
        run: ./test_all.sh
