name: Dart CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer

jobs:
  test:
    name: Test ${{ matrix.package }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        package:
          [
            pending_operations,
            sign_in_with_apple/sign_in_with_apple,
            sign_in_with_apple/sign_in_with_apple_platform_interface,
            state_queue_test,
            state_queue,
            with_bloc,
          ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: "2.5.1"
      - name: Install dependencies
        run: flutter packages get
        working-directory: packages/${{ matrix.package }}
      - name: Analyze
        run: flutter analyze
        working-directory: packages/${{ matrix.package }}
      - name: Format
        run: flutter format --set-exit-if-changed .
        working-directory: packages/${{ matrix.package }}
      - name: Run tests
        run: flutter test --coverage
        working-directory: packages/${{ matrix.package }}
      - name: Upload coverage to Codecov
        if: startsWith(matrix.os, 'macos')
        uses: codecov/codecov-action@v1.0.6
        with:
          flags: ${{ matrix.package }}
          name: ${{ matrix.package }}
          fail_ci_if_error: false

  build-ios:
    name: Build ${{ matrix.package }} iOS on ${{ matrix.os }} with Xcode ${{ matrix.xcode }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        package:
          [sign_in_with_apple/sign_in_with_apple]
        xcode:
          ["12.5.1", "13.0"]
        flutter:
          ["2.5.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Build iOS
        run: flutter build ios --no-codesign
        working-directory: packages/${{ matrix.package }}/example
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  build-android:
    name: Build ${{ matrix.package }} Android on ${{ matrix.os }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        package:
          [sign_in_with_apple/sign_in_with_apple]
        flutter:
          ["2.5.3"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # OpenJDK
          java-version: '11' # Specific (older) version needed for Gradle wrapper
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Build Android
        run: flutter build appbundle
        working-directory: packages/${{ matrix.package }}/example

  build-macos:
    name: Build ${{ matrix.package }} macOS on ${{ matrix.os }} with Xcode ${{ matrix.xcode }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
        package:
          [sign_in_with_apple/sign_in_with_apple]
        xcode:
          ["12.5.1", "13.0"]
        flutter:
          ["2.5.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Xcode select
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Enable macOS Desktop Integration
        run: flutter config --enable-macos-desktop
      - name: Build macOS
        run: flutter build macos
        working-directory: packages/${{ matrix.package }}/example
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

  build-web:
    name: Build ${{ matrix.package }} Web on ${{ matrix.os }} and Flutter ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        package:
          [sign_in_with_apple/sign_in_with_apple]
        flutter:
          ["2.5.3"]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1.5.3
        with:
          flutter-version: ${{ matrix.flutter }}
      - name: Build Web
        run: flutter build web
        working-directory: packages/${{ matrix.package }}/example