name: Dart CI

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-10.15]
        package: [pending_operations, sign_in_with_apple]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@c1bf65eb311fe29b5bc99d6e91c4498decde268a # v1.3.0
        with:
          flutter-version: "1.12.13+hotfix.8"
      - name: Go to package
        run: cd packages/${{ matrix.package }}
      - name: Install dependencies
        run: flutter packages get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
